# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('payment_mode', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
